I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/Alinor.rpy", line 86, in script
    call screen imagebutton_example
ScriptError: could not find label '.to_jack_home'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "D:\Programms\Renpy\renpy-6.99.14.1-sdk\renpy\bootstrap.py", line 306, in bootstrap
    renpy.main.main()
  File "D:\Programms\Renpy\renpy-6.99.14.1-sdk\renpy\main.py", line 523, in main
    run(restart)
  File "D:\Programms\Renpy\renpy-6.99.14.1-sdk\renpy\main.py", line 149, in run
    renpy.execution.run_context(True)
  File "D:\Programms\Renpy\renpy-6.99.14.1-sdk\renpy\execution.py", line 835, in run_context
    context.run()
  File "game/Alinor.rpy", line 86, in script
    call screen imagebutton_example
  File "D:\Programms\Renpy\renpy-6.99.14.1-sdk\renpy\script.py", line 871, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label '.to_jack_home'.

Windows-7-6.1.7601-SP1
Ren'Py 6.99.14.1.3218
 
Wed Nov 14 16:33:07 2018
